/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { Generated, ColumnType } from 'kysely';

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountPlan {
  description: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  isDefault: Generated<boolean>;
  isDeleted: Generated<boolean>;
  plan: Json | null;
  priceMonthly: Generated<Numeric>;
  priceYearly: Generated<Numeric>;
  title: string;
}

export interface AccountRole {
  description: string | null;
  id: number;
  isActive: Generated<boolean>;
  isDefault: Generated<boolean>;
  isDeleted: Generated<boolean>;
  name: string;
}

export interface AccountsRole {
  accountId: number;
  accountRoleId: number;
}

export interface AssetClass {
  active: Generated<boolean>;
  code: string;
  createdAt: Generated<Timestamp>;
  deleted: Generated<boolean>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Locale {
  active: Generated<boolean>;
  code: string;
  createdAt: Generated<Timestamp>;
  deleted: Generated<boolean>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Market {
  active: Generated<boolean>;
  code: string;
  createdAt: Generated<Timestamp>;
  deleted: Generated<boolean>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Session {
  expired: Timestamp;
  sess: Json;
  sid: string;
}

export interface Ticker {
  active: Generated<boolean>;
  cik: number;
  compositeFigi: string;
  createdAt: Generated<Timestamp>;
  currencyName: string;
  deleted: Generated<boolean>;
  delisted: Timestamp | null;
  id: Generated<number>;
  lastUpdated: Timestamp;
  localeId: number;
  marketId: number;
  name: string;
  primaryExchange: string;
  ticker: string;
  tickerTypeId: number;
  updatedAt: Generated<Timestamp>;
}

export interface TickerType {
  active: Generated<boolean>;
  assetClassId: number;
  code: string;
  createdAt: Generated<Timestamp>;
  deleted: Generated<boolean>;
  description: string;
  id: Generated<number>;
  localeId: number;
  updatedAt: Generated<Timestamp>;
}
