/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType, Generated } from 'kysely';

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountPlan {
  description: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  isDefault: Generated<boolean>;
  isDeleted: Generated<boolean>;
  plan: Json | null;
  priceMonthly: Generated<Numeric>;
  priceYearly: Generated<Numeric>;
  title: string;
}

export interface AccountRole {
  description: string | null;
  id: number;
  isActive: Generated<boolean>;
  isDefault: Generated<boolean>;
  isDeleted: Generated<boolean>;
  name: string;
}

export interface AccountsRole {
  accountId: number;
  accountRoleId: number;
}

export interface Session {
  expired: Timestamp;
  sess: Json;
  sid: string;
}
